openapi: 3.1.0
info:
  title: Google Docs Edit & Restore API
  description: Allows automated editing, downloading, and restoration of Google Docs.
  version: 1.0.0
servers:
  - url: https://docs.googleapis.com
    description: Google Docs API
paths:
  /v1/documents/{documentId}:
    get:
      operationId: getDocument
      summary: Retrieve a Google Document
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document content
          content:
            application/json:
              schema:
                type: object
Fix servers block format for GPT Builder

